name: flutter_devtools
description: "A new Flutter project to demo DevTools"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  odometer: ^3.0.0
  talker_bloc_logger: ^2.4.0
  talker_dio_logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  fonts:
    - family: Octicons
      fonts:
        - asset: fonts/Octicons.ttf

  assets:
    - assets/good/
    - assets/bad/